### ISSUE TITLE
raspberry-tie does not run with a real SenseHAT

### ISSUE THREAD

**Issue by torstenandrecht** [JanLahmann/RasQberry-Two#12]
ython3 -c "import sense_hat" fails because of missing RTMU / RTIMULib:
(RQB2) rasqberry@rasqberry-two:~ $ python3 -c "import sense_hat"
Traceback (most recent call last):
 File "<string>", line 1, in <module>
 File "/home/rasqberry/RasQberry-Two/venv/RQB2/lib/python3.11/site-packages/sense_hat/__init__.py", line 2, in <module>
  from .sense_hat import SenseHat, SenseHat as AstroPi
 File "/home/rasqberry/RasQberry-Two/venv/RQB2/lib/python3.11/site-packages/sense_hat/sense_hat.py", line 11, in <module>
  import RTIMU # custom version
  ^^^^^^^^^^^^
ModuleNotFoundError: No module named 'RTIMU'
This cannot be installed easily (pip install pip install RTIMULib fails.)
Interestingly, RTIMU is installed in the default python environment, but not in our RQB2 venv.
I assume it gets installed in stage 5, after we create our venv. But haven't checked.
I also assume (after some testing in the default python env), that if we have RTIMU/RTIMULib in our RQB2 venv, then the real SenseHAt will work.

[@Rishi](https://ibm-volkswagen-group.slack.com/team/U0295B79FMM)
 I think we need to add the flag --system-site-packages when creating our venv in https://github.com/JanLahmann/RasQberry-pi-gen/blob/34f123ba0d96b2c94e9e1984cf98b242f3fa1360/stage5/qiskit-setup-run.sh#L40C1-L40C16. Then we should see sense-hat and RTIMU in the venv as well, without explicit/additional install in the venv.

**Comment by JanLahmann** [comment]
solved with https://github.com/JanLahmann/RasQberry-pi-gen/pull/13 and https://github.com/JanLahmann/RasQberry-Two/commit/d19c348d38f844872077e44508a9e5db463d1576
Needs verification.
